# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_plan_before'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='max_evacuation_time',
            field=models.PositiveIntegerField(blank=True, help_text='in seconds', null=True, verbose_name='Maximum Evacuation Time'),
        ),
    ]
