# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-15 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_auto_20160212_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='max_evacuation_time',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Maximum Evacuation Time in Sec'),
        ),
    ]
