# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-27 11:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0007_plan_leader'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['name']},
        ),
    ]
