# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-04 12:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0008_auto_20160627_1116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connection',
            options={'ordering': ['seq']},
        ),
    ]
