# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-08 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0004_auto_20160705_0822'),
        ('plans', '0009_auto_20160704_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='tag_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tags.Tag'),
        ),
    ]
