# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-08 09:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0010_plan_tag_leader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='leader',
        ),
    ]
