# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20160107_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='organization',
            field=models.CharField(blank=True, choices=[('uoa', 'University of Athens'), ('eppo', 'EPPO'), ('uoc', 'UoC-NHMC'), ('vez', 'Vesuvius Observatory'), ('cei', 'CEI'), ('incd', 'INCD "URBAN-INCERC"')], max_length=6, null=True),
        ),
    ]
