# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-24 11:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preparednessquestionnaireanswer',
            old_name='building',
            new_name='questionnaire',
        ),
        migrations.AlterUniqueTogether(
            name='preparednessquestionnaireanswer',
            unique_together=set([('questionnaire', 'question')]),
        ),
    ]
