# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-23 11:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EvacuationQuestionnaire',
            new_name='PreparednessQuestionnaire',
        ),
        migrations.RenameModel(
            old_name='EvacuationQuestionnaireAnswer',
            new_name='PreparednessQuestionnaireAnswer',
        ),
        migrations.RenameModel(
            old_name='EvaluationQuestionnaireQuestion',
            new_name='PreparednessQuestionnaireQuestion',
        ),
    ]
