# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-25 08:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experiments', '0003_auto_20160202_1130'),
        ('questionnaires', '0002_auto_20160525_0837'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationQuestionnaireAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=3)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experiments.Experiment')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaires.EvaluationQuestionnaireQuestion')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='evaluationquestionnaireanswer',
            unique_together=set([('experiment', 'question')]),
        ),
    ]
