# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-24 11:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0002_auto_20160524_1104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preparednessquestionnaireanswer',
            old_name='questionnaire',
            new_name='building',
        ),
        migrations.AlterUniqueTogether(
            name='preparednessquestionnaireanswer',
            unique_together=set([('building', 'question')]),
        ),
    ]
