# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-25 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experiments', '0003_auto_20160202_1130'),
        ('questionnaires', '0004_evaluationstudentsquestionnaire_evaluationstudentsquestionnaireanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationTeachersQuestionnaireAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=3)),
                ('ip', models.GenericIPAddressField()),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experiments.Experiment')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationTeachersQuestionnaireQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=240)),
            ],
        ),
        migrations.RenameModel(
            old_name='EvaluationStudentsQuestionnaire',
            new_name='EvaluationStudentsQuestionnaireQuestion',
        ),
        migrations.AddField(
            model_name='evaluationteachersquestionnaireanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaires.EvaluationTeachersQuestionnaireQuestion'),
        ),
    ]
