# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-05 08:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_auto_20160705_0807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag_id',
            new_name='tag_string',
        ),
    ]
