# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-05 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_auto_20160705_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_string',
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
