# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-30 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0004_auto_20160705_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_string',
            field=models.TextField(unique=True),
        ),
    ]
