# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='exucation_date',
            new_name='execuation_date',
        ),
    ]
