# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-12 09:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experiments', '0003_auto_20160202_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckpointReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_flux', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fail', models.BooleanField(default=False)),
                ('checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experiments.Checkpoint')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experiments.Experiment')),
            ],
        ),
    ]
