# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-04 12:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_checkpointfailplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpointfailplan',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 4, 12, 25, 12, 162193, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkpointreport',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 4, 12, 25, 19, 718237, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
