# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-08 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_auto_20160704_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpointfailplan',
            name='tag',
            field=models.CharField(max_length=70),
        ),
    ]
