# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-08 09:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0004_auto_20160705_0822'),
        ('analytics', '0005_auto_20160708_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpointfailplan',
            name='tag_r',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tags.Tag'),
        ),
    ]
