# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-08 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_checkpointfailplan_tag_r'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkpointfailplan',
            name='tag',
        ),
    ]
