# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-08 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_remove_checkpointfailplan_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpointfailplan',
            name='tag_r',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags.Tag'),
        ),
    ]
