# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-27 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_auto_20160708_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpointfailplan',
            name='error_code',
            field=models.CharField(choices=[('1', 'Correct Execution'), ('2', 'Path Before Path'), ('3', 'Teacher')], default='1', max_length=2),
            preserve_default=False,
        ),
    ]
