# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-05 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_checkpointfailplan_error_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpointfailplan',
            name='number_of_students_teacher_error',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
