# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-23 09:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EvaluationQuestionnaire',
            new_name='EvaluationQuestionnaireQusetions',
        ),
    ]
