# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-23 09:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_auto_20160523_0948'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EvaluationQuestionnaireQusetions',
            new_name='EvaluationQuestionnaireQuestion',
        ),
    ]
