# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-23 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0004_evacuationquestionnaire_evacuationquestionnaireanswers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evacuationquestionnaireanswers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.EvaluationQuestionnaireQuestion'),
        ),
        migrations.AlterUniqueTogether(
            name='evacuationquestionnaireanswers',
            unique_together=set([('questionnaire', 'question')]),
        ),
    ]
