# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-23 10:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0005_auto_20160523_1013'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EvacuationQuestionnaireAnswers',
            new_name='EvacuationQuestionnaireAnswer',
        ),
    ]
