# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 14:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('country', models.CharField(choices=[('gr', 'Greece'), ('rm', 'Romania')], max_length=2)),
                ('address', models.CharField(blank=True, max_length=30, null=True)),
                ('tk', models.PositiveIntegerField(blank=True, null=True)),
                ('max_evacuation_time', models.PositiveIntegerField(blank=True, help_text='in seconds', null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='building_images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('number', models.PositiveSmallIntegerField()),
                ('blueprint', models.ImageField(upload_to='blueprints/')),
                ('max_evacuation_time', models.PositiveIntegerField(blank=True, help_text='in seconds', null=True)),
                ('stud_number', models.PositiveIntegerField(blank=True, null=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.Building')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
