# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 13:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 1, 12, 13, 20, 30, 985660, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
