# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-07 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_auto_20160107_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='building_images/'),
        ),
        migrations.AlterField(
            model_name='building',
            name='max_evacuation_time',
            field=models.PositiveIntegerField(blank=True, help_text='in seconds', null=True),
        ),
    ]
