# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-08 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0003_auto_20160107_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('number', models.PositiveSmallIntegerField()),
                ('blueprint', models.ImageField(upload_to='blueprints/')),
                ('max_evacuation_time', models.PositiveIntegerField(blank=True, help_text='in seconds', null=True)),
                ('stud_number', models.PositiveIntegerField(blank=True, null=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.Building')),
            ],
        ),
    ]
