# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 13:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0003_building_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 1, 12, 13, 21, 10, 465277, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='floor',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 1, 12, 13, 21, 14, 251388, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
