# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0004_auto_20160112_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='country',
            field=models.CharField(choices=[('gr', 'Greece'), ('rm', 'Romania'), ('bg', 'Bulgaria'), ('it', 'Italy')], max_length=2),
        ),
        migrations.AlterField(
            model_name='building',
            name='max_evacuation_time',
            field=models.PositiveIntegerField(blank=True, help_text='in seconds', null=True, verbose_name='Maximum Evacuation Time'),
        ),
        migrations.AlterField(
            model_name='floor',
            name='max_evacuation_time',
            field=models.PositiveIntegerField(blank=True, help_text='in seconds', null=True, verbose_name='Maximum Evacuation Time'),
        ),
        migrations.AlterField(
            model_name='floor',
            name='stud_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of students'),
        ),
    ]
