# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-08 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0005_auto_20160202_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='photo',
            field=models.ImageField(blank=True, help_text='Supported Formats: png, jpg, jpeg, bmp', null=True, upload_to='building_images/'),
        ),
        migrations.AlterField(
            model_name='building',
            name='tk',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Postcode'),
        ),
        migrations.AlterField(
            model_name='floor',
            name='number',
            field=models.SmallIntegerField(verbose_name='Floor Level'),
        ),
    ]
